services:
  app:
    env_file: .env
    image: "aviumlabs/phoenix:latest-alpine" 
    volumes:
      - ./src:${APP_CONTAINER_ROOT}
    ports:
      - "4000:4000"
    working_dir: ${WORKINGDIR}
    depends_on:
      - db
  db:
    env_file: .env
    image: "postgres:15.2-alpine"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
